#!/usr/bin/env bash

die() { printf %s "${@+$@$'\n'}" 1>&2 ; exit 1 ; }

# other choco commands
#  `choco uninstall -x pkgnm` remove package and all dependencies
#  `choco upgrade -y all` upgrade all installed package

pkgs=(
# "ffmpeg"  # removed since choco version is incompatible with my bash scripts for unknown reasons
  "calibre"
  'git.install --params "/GitAndUnixToolsOnPath /WindowsTerminal /NoCredentialManager /NoAutoCrlf"'
  "irfanview" "irfanviewplugins"
  "make"  # GNU make
  "mpc-hc-clsid2"
  "ripgrep"
  "shellcheck"
  "totalcommander"
  "universal-ctags"
  "wget"
  "xmlstarlet"
  "zulu11"
  )

command -v choco > /dev/null || die "need to install choco; use install_chocolatey.bat"

cinst() (
   set -x
   choco install -y "$@"
   )

# cinst git.install --params "/GitAndUnixToolsOnPath /WindowsTerminal /NoCredentialManager /NoAutoCrlf"
cinst "${pkgs[@]}"
