#!/usr/bin/env bash

die() { printf %s "${@+$@$'\n'}" 1>&2 ; exit 1 ; }
see() ( { set -x; } 2>/dev/null ; "$@" ) ;

# NB: PWS is installed manually https://pwsafe.org/

pwsexe="$PROGRAMFILES\Password Safe\pwsafe.exe"  # dflt x64 install locn
[[ -x "$pwsexe" ]] || die "$pwsexe not found"
set -x
safe_fnm="${PWSAFE_FNM:-"$PWD/kgpass.lib"}"
# [[ "$PWSAFE_FNM" ]] || die '$PWSAFE_FNM (abs path to safe file) is not defined?'
[[ -f "$safe_fnm" ]] || die "$safe_fnm is not a file?"
safe_fnmw="$(cygpath -aw "$safe_fnm")" # ; echo "safe_fnmw=$safe_fnmw"
see start '""' "$pwsexe" "$safe_fnmw"
